### ISSUE TITLE
Built in styles that affect children broken in editor preview

### ISSUE THREAD

**Issue by samiresua** [contentful/experience-builder#551]
Built in styles that change the way children render such as `cfHorizontalAlignment`, `cfVerticalAlignment`, `cfGap`, `cfFlexWrap`, `cfFlexDirection` don't seem to have any effect in the editor preview, this issue seems to be happening because of a wrapping element added for the purpose of dragging elements around the canvas.

I have worked around this issue for now with the following css in my project

```css
[data-rfd-droppable-id] {
    justify-content: inherit;
    justify-items: inherit;
    align-items: inherit;
    align-content: inherit;
    gap: inherit;
    flex-wrap: inherit;
    flex-direction: inherit;
    display: inherit;
}
```
